on:
  push:
     branches:
       - "[Ff]eature-*" 

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown","HelpersMG","readr"))'
        
      - uses: r-lib/actions/setup-tinytex@v1
      - name : install tinytex
        run: tlmgr --version
    
      - name: Render Book
        run: |
             Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::epub_book", output_dir="docs")'
             Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::word_document2", output_dir="docs")'
             Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook", output_dir="docs")'
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs/

