on:
  pull_request:
     branches:
       - "[Ff]eature-gh-pages_*"

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown","HelpersMG","readr"))'
        
      - uses: r-lib/actions/setup-tinytex@v1
      - name : install tinytex
        run: tlmgr --version
    
      - name: Render Book
        run: |
             Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::epub_book", output_dir="docs")'
             Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::word_document2", output_dir="docs")'
             Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook", output_dir="docs")'
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs/
# deploy to gh pages yml
  build-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
           
        #- name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
        #uses: actions/download-artifact@v1
        #with:
          #name: docs
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs
          TARGET_FOLDER: docs # The folder the action should deploy.
          CLEAN: true
      
      
